#!/usr/bin/env python3
# Copyright (c) 2026 jesus luque.
"""One USD stage per material, on the CPU: the shader ball (scene/base.usda) with the
material bound to both its meshes. Writes, under MATX_WORK (generated, not in git),
scene/base.usda (from scene/base.usda.in), materials/<id>.usda (the .mtlx through usdMtlx,
by usdcat) and stages/<id>.usda; and, beside this script (in git), manifest.json: every
material's phase, source, licence, lobe classes, status, and why when skipped, with
portable paths (a stage relative to MATX_WORK, a .mtlx relative to its library's root).

  python3 build_ball.py && bash fetch_phase2.sh && python3 build_stages.py

How a material is bound -- as athenea reads MaterialX from USD: a Material whose
`outputs:mtlx:surface` connects to a Shader of `info:id` ND_<node>_surfaceshader
(the Corvette's looks, tests/data/lobes). usdMtlx writes exactly that, under
/MaterialX/Materials, with node graphs under /MaterialX/NodeGraphs; the whole
/MaterialX scope is referenced in as /World/Looks so its connections stay whole.

Two fixes made at authoring, both automatic:
  - texture paths: usdMtlx keeps them relative to the .mtlx; they are made absolute;
  - colour space: OpenPBR's examples are `colorspace="acescg"`, which athenea does not
    read for constants (only a texture's colorSpace), so their color3 constants are
    converted ACEScg -> linear Rec.709 here (clamped to [0, 1]) and the manifest says so.
"""
import glob
import json
import os
import re
import subprocess
import sys

import matx_common as m

MAT_DIR = os.path.join(m.WORK, "materials")
STAGE_DIR = os.path.join(m.WORK, "stages")

AP1_TO_709 = ((1.70505, -0.62179, -0.08326),
              (-0.13026, 1.14080, -0.01055),
              (-0.02400, -0.12897, 1.15297))


def acescg_to_709(match):
    rgb = [float(x) for x in match.group(2).split(",")]
    out = [min(1.0, max(0.0, sum(AP1_TO_709[r][c] * rgb[c] for c in range(3)))) for r in range(3)]
    return f"{match.group(1)}({out[0]:.6g}, {out[1]:.6g}, {out[2]:.6g})"


def to_usda(mtlx, out, space):
    r = subprocess.run([m.USDCAT, mtlx], capture_output=True, text=True)
    if r.returncode != 0:
        return None, (r.stderr or r.stdout).strip()[-400:]
    text = r.stdout
    base = os.path.dirname(mtlx)
    # Absolute texture paths.
    text = re.sub(r"@([^@]+)@", lambda mm: "@" + (mm.group(1) if os.path.isabs(mm.group(1)) or mm.group(1).startswith("/")
                                                  else os.path.normpath(os.path.join(base, mm.group(1)))) + "@", text)
    missing = [p for p in re.findall(r"@([^@]+)@", text) if not os.path.exists(p)]
    if missing:
        return None, "missing textures: " + ", ".join(missing)
    converted = 0
    if space == "acescg":
        text, converted = re.subn(r"(color3f inputs:\w+ = )\(([^)]*)\)", acescg_to_709, text)
        text = text.replace('string colorSpace = "acescg"', 'string colorSpace = "lin_rec709"')
    open(out, "w").write(text)
    mats = re.findall(r'def Material "([^"]+)"', text)
    return {"materials": mats, "colour_constants_converted": converted}, None


def stage_text(ident, mat_name, source):
    return f'''#usda 1.0
(
    defaultPrim = "World"
    metersPerUnit = 1
    upAxis = "Y"
    subLayers = [@../scene/base.usda@]
    doc = """Copyright (c) 2026 jesus luque.
    matx: {ident} ({source}) bound to both meshes of the shader ball. Generated by build_stages.py."""
)

over "World"
{{
    def Scope "Looks" (
        prepend references = @../materials/{ident}.usda@</MaterialX>
    )
    {{
    }}

    over "ShaderBall"
    {{
        over "Preview_Mesh" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            rel material:binding = </World/Looks/Materials/{mat_name}>
        }}

        over "Calibration_Mesh" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            rel material:binding = </World/Looks/Materials/{mat_name}>
        }}
    }}
}}
'''


def entries():
    for fam in m.MX_FAMILIES:
        for f in sorted(glob.glob(os.path.join(m.MX_EXAMPLES, fam, "*.mtlx"))):
            name = os.path.basename(f)[:-5]
            yield {"id": "mx_" + name, "phase": 1, "family": fam, "root": "mx", "mtlx": os.path.relpath(f, m.MX_EXAMPLES),
                   "source": "MaterialX resources/Materials/Examples (MaterialX 1.39, Apache-2.0)",
                   "skip": m.MX_SKIPPED.get(name)}
    for name in m.PHASE2_OPENPBR:
        f = os.path.join(m.OPENPBR_CACHE, f"open_pbr_{name}.mtlx")
        yield {"id": "opbr_" + name, "phase": 2, "family": "OpenPBR examples", "root": "openpbr",
               "mtlx": os.path.basename(f),
               "source": f"AcademySoftwareFoundation/OpenPBR@{m.OPENPBR_COMMIT[:10]} examples (Apache-2.0)",
               "url": m.OPENPBR_URL + f"open_pbr_{name}.mtlx",
               "skip": None if os.path.exists(f) else "not fetched (run fetch_phase2.sh)"}


def main():
    os.makedirs(MAT_DIR, exist_ok=True)
    os.makedirs(STAGE_DIR, exist_ok=True)
    os.makedirs(os.path.join(m.WORK, "scene"), exist_ok=True)
    if not os.path.exists(os.path.join(m.WORK, "scene", "shaderball.usdc")):
        sys.exit("no scene/shaderball.usdc under MATX_WORK: run build_ball.py first")
    if not os.path.exists(m.AUTOSHOP):
        sys.exit(f"no autoshop HDRI at {m.AUTOSHOP} (MATX_AUTOSHOP)")
    template = open(os.path.join(m.SRC, "scene", "base.usda.in")).read()
    open(os.path.join(m.WORK, "scene", "base.usda"), "w").write(template.replace("@@AUTOSHOP@@", "@" + m.AUTOSHOP + "@"))
    manifest = []
    for e in entries():
        mtlx = m.mtlx_path(e)
        if os.path.exists(mtlx):
            e["classes"], e["surface"], e["textured"], e["colorspace"] = m.classify(mtlx)
        if not e["skip"]:
            info, err = to_usda(mtlx, os.path.join(MAT_DIR, e["id"] + ".usda"), e.get("colorspace"))
            if err:
                e["skip"] = "usdMtlx: " + err
            elif len(info["materials"]) != 1:
                e["skip"] = f"{len(info['materials'])} materials in the document; the study binds one"
            else:
                e["material"] = info["materials"][0]
                e["colour_constants_converted"] = info["colour_constants_converted"]
                stage = os.path.join(STAGE_DIR, e["id"] + ".usda")
                open(stage, "w").write(stage_text(e["id"], e["material"], e["source"]))
                chk = subprocess.run([m.USDCHECKER, stage], capture_output=True, text=True)
                e["usdchecker"] = "ok" if chk.returncode == 0 else (chk.stdout + chk.stderr).strip()[-300:]
                e["stage"] = os.path.relpath(stage, m.WORK)
        e["status"] = "skipped" if e["skip"] else "ok"
        manifest.append(e)
        print(f"{e['status']:8} {e['id']:42} {','.join(e.get('classes', []))}  {e['skip'] or e.get('usdchecker', '')}")
    manifest += [dict(d, phase=2, status="deferred") for d in m.PHASE2_DEFERRED]
    json.dump(manifest, open(m.MANIFEST, "w"), indent=1)
    ok = sum(1 for e in manifest if e["status"] == "ok")
    print(f"{ok} stages, {sum(1 for e in manifest if e['status'] == 'skipped')} skipped, "
          f"{sum(1 for e in manifest if e['status'] == 'deferred')} deferred -> manifest.json")


if __name__ == "__main__":
    sys.exit(main())
