#!/usr/bin/env bash
# Builds OpenUSD for athenea into ~/tools/usd-<version>-mx.
#
# Why a script and not FetchContent: OpenUSD takes tens of minutes and brings
# its own oneTBB, OpenSubdiv and friends. Building it once per machine, next to
# ~/tools/slang, keeps the engine's configure step in seconds. The engine then
# links the oneTBB this build installs, so there is one TBB in the process.
#
# Why no Python: OpenUSD 26.08 does not yet support the Python 3.14 that
# Homebrew ships, and the engine needs none of it -- the PLY -> USD converter is
# `athenea convert`, in C++. usdview is therefore not built; `athenea view` is the viewer.
#
# With MaterialX (1.39.5, whose Slang generator the engine's materials are
# generated by) and OpenVDB with NanoVDB (volumes reach the GPU as NanoVDB
# grids). MATERIALX_SLANG_RHI_SOURCE_DIR stays unset: MaterialX's own Slang
# renderer would bring a second slang-rhi into the process.
#
# The prefix carries "-mx" so the previous build stays usable until the engine
# is green against this one.
#
# THE SPECIFICATION IS A LIVING ONE. A release lands every three months or
# so, and the engine is held to the current one (docs/decisions.md, "The spec
# is the reference, and it is a living one"). So besides a tag this takes
# `dev`, the branch the next release is cut from, into its own prefix
# (~/tools/usd-dev-mx): that is built on the Linux machine first, and the Mac
# stays on the release until the engine is green against the new one. What
# to match when moving, from the release's VERSIONS.md (26.08): oneTBB 2021.9
# and OpenVDB 10.1.0 (build_usd.py brings both), OpenSubdiv 3.6.1, MaterialX
# 1.39.5 (the engine's own generator target), CMake 3.27 or later, Apple
# clang 16 / gcc 11.5. And what a release deprecates, to read before
# building: 26.03 made the scene delegate path deprecated (this delegate is
# on the scene index path), and moved displayName/displayGroup/hidden to
# uiHints (the schemas here author none); 26.08 deprecated SdfTimeCode for
# GfTimeCode (unused here) and HdRenderIndex::New outside emulation, which
# is exactly the emulation this delegate is driven through.
#
# Usage: scripts/build-usd.sh [version|dev]   (default v26.08)
set -euo pipefail

VERSION="${1:-v26.08}"
PREFIX="${ATHENEA_USD_ROOT:-$HOME/tools/usd-${VERSION#v}-mx}"
SRC="${ATHENEA_USD_SRC:-$HOME/tools/src/OpenUSD-${VERSION#v}}"
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN)}"

if [[ ! -d "$SRC/.git" ]]; then
    mkdir -p "$(dirname "$SRC")"
    git clone --depth 1 --branch "$VERSION" \
        https://github.com/PixarAnimationStudios/OpenUSD.git "$SRC"
elif [[ "$VERSION" == "dev" ]]; then
    # A branch moves: the checkout follows it, where a tag's stays put.
    git -C "$SRC" fetch --depth 1 origin dev
    git -C "$SRC" checkout -q FETCH_HEAD
fi
echo "OpenUSD ${VERSION} at $(git -C "$SRC" rev-parse --short HEAD), into ${PREFIX}"

# CMake 4 refuses projects declaring compatibility with CMake < 3.5, which
# c-blosc (an OpenVDB dependency) still does.
export CMAKE_POLICY_VERSION_MINIMUM=3.5

# Homebrew's libraries must not leak into the build; the flag exists only in
# build_usd.py's macOS options.
PLATFORM_ARGS=()
if [[ "$(uname)" == "Darwin" ]]; then
    PLATFORM_ARGS+=(--ignore-homebrew)
fi

# A TBB the process already has, instead of the one build_usd.py would build
# (ATHENEA_USD_TBB=<prefix>, e.g. /opt/homebrew/opt/tbb). An embedder whose own
# libraries already link a oneTBB -- the compositor's OpenImageIO links
# Homebrew's -- otherwise carries two, USD's and its own. build_usd.py counts
# oneTBB as installed when `include/oneapi/tbb.h` is in the prefix, so the
# host's is linked into it and every dependency -- OpenVDB, OpenSubdiv, USD --
# links that one. libtbb.12 is backward compatible, and Homebrew's names
# itself by absolute path, so the process loads one image of it.
if [[ -n "${ATHENEA_USD_TBB:-}" ]]; then
    mkdir -p "$PREFIX/include" "$PREFIX/lib/cmake"
    ln -sfn "$ATHENEA_USD_TBB/include/oneapi" "$PREFIX/include/oneapi"
    ln -sfn "$ATHENEA_USD_TBB/include/tbb" "$PREFIX/include/tbb"
    for lib in "$ATHENEA_USD_TBB"/lib/libtbb*; do
        ln -sfn "$lib" "$PREFIX/lib/$(basename "$lib")"
    done
    ln -sfn "$ATHENEA_USD_TBB/lib/cmake/TBB" "$PREFIX/lib/cmake/TBB"
    echo "TBB: ${ATHENEA_USD_TBB}, linked into ${PREFIX}"
    # OpenVDB 10.1 picks its cancellation call by TBB_INTERFACE_VERSION and
    # expects <tbb/task.h> to have defined it. oneTBB's task.h stopped
    # including version.h after 2021, so against a newer TBB the macro is
    # undefined, the old branch is taken, and `tbb::task::self()` -- gone
    # since 2021 -- fails to compile. Including version.h first puts it back.
    OPENVDB_TBB_ARGS="-DCMAKE_CXX_FLAGS=-includetbb/version.h"
fi

PYTHON="$(command -v python3)"
"$PYTHON" "$SRC/build_scripts/build_usd.py" \
    --build-variant release \
    --no-python \
    --no-docs \
    --no-tests \
    --no-tutorials \
    --materialx \
    --no-embree \
    --no-ptex \
    --openvdb \
    --build-args "OpenVDB,-DOPENVDB_BUILD_NANOVDB=ON -DNANOVDB_USE_OPENVDB=ON ${OPENVDB_TBB_ARGS:-}" \
    --no-openimageio \
    --no-opencolorio \
    --onetbb \
    --usd-imaging \
    "${PLATFORM_ARGS[@]}" \
    --tools \
    --examples \
    -j "$JOBS" \
    "$PREFIX"

# GCC 13 rejects the injected-class-name written with its template arguments
# in a constructor of the bool specialisation (retainedDataSource.h:235,
# `HdRetainedTypedSampledDataSource<bool>(const bool&)`); clang accepts it.
# Only translation units that include the header meet it, which the light
# linking's retained data sources do. Patched in place so the prefix is the
# same one the Mac and the Linux machine build against.
HDR="$PREFIX/include/pxr/imaging/hd/retainedDataSource.h"
if grep -q "HdRetainedTypedSampledDataSource<bool>(const bool& value)" "$HDR"; then
    sed -i.orig "s/HdRetainedTypedSampledDataSource<bool>(const bool& value)/HdRetainedTypedSampledDataSource(const bool\& value)/" "$HDR"
    echo "patched ${HDR} for GCC 13"
fi

echo "OpenUSD ${VERSION} installed at ${PREFIX}"
echo "Configure athenea with -DATHENEA_USD_ROOT=${PREFIX} (the presets default to it)."
